apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus
  namespace: kube-system
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 192.168.13.57
    path: /app/k8s