## Service
kind: Service
apiVersion: v1
metadata:
  name: mysql-server
  namespace: caas
  labels:
    k8s-app: mysql-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    k8s-app: mysql-server
  clusterIP: None
  type: ClusterIP
  sessionAffinity: None